steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/container-name/app:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west4-docker.pkg.dev/$PROJECT_ID/container-name/app:$SHORT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'container-service'
      - '--image'
      - 'europe-west4-docker.pkg.dev/$PROJECT_ID/container-name/app:$SHORT_SHA'
      - '--region'
      - 'europe-west4'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--project'
      - '$PROJECT_ID'

images:
  - 'europe-west4-docker.pkg.dev/$PROJECT_ID/container-name/app:$SHORT_SHA'

substitutions:
  _SERVICE_NAME: 'container-service'
timeout: '1200s'
